### ISSUE TITLE
Check if readme is up to date and change as necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer-machine-learning#16]
It is a good time for this task now. You are in the best position for this issue, @danielgoldelman.

**Comment by SebastianZimmeck** [comment]
This can be done in connection with [doublechecking the ML results](https://github.com/privacy-tech-lab/privacy-pioneer-paper/issues/19).

**Comment by danielgoldelman** [comment]
Readme is up to date, ml results verified.
